In [1]:
from link_prediction.profiling import prepare_benchmark

In [2]:
network_profiles, dataset_manifest = prepare_benchmark(
    benchmark_name="standard",
    overwrite=False,
)

network_profiles

network profiling: 8 tasks, 6 workers

,network,domain,raw_graph_type,raw_directed,raw_nodes,raw_edges,raw_undirected_nodes,raw_undirected_edges,raw_components,processed_nodes,...,largest_component_node_ratio,largest_component_edge_ratio,density,average_degree,average_clustering,transitivity,degree_assortativity,processed_components,network_id,repository
0,email-Eu-core,communication,DiGraph,True,1005,25571,1005,16064,20,986,...,0.981095,1.000000,0.033080,32.584178,0.407050,0.267392,-0.025743,1,email_eu_core,SNAP
1,email-univ,communication,Graph,False,1133,5451,1133,5451,1,1133,...,1.000000,1.000000,0.008500,9.622242,0.220176,0.166250,0.078201,1,email_univ,Network Data Repository
2,power-1138-bus,infrastructure,Graph,False,1138,2596,1138,1458,1,1138,...,1.000000,1.000000,0.002254,2.562390,0.086615,0.093068,-0.080110,1,power_1138_bus,Network Data Repository
3,power-grid,infrastructure,Graph,False,4941,6594,4941,6594,1,4941,...,1.000000,1.000000,0.000540,2.669095,0.080104,0.103153,0.003457,1,power_grid,Netzschleuder
4,ca-GrQc,scientific_collaboration,Graph,False,5242,14496,5242,14484,355,4158,...,0.793209,0.926678,0.001553,6.455988,0.556878,0.628894,0.639186,1,ca_grqc,SNAP
5,ca-HepTh,scientific_collaboration,Graph,False,9877,25998,9877,25973,429,8638,...,0.874557,0.955069,0.000665,5.743459,0.481564,0.281129,0.238915,1,ca_hepth,SNAP
6,ego-Facebook,social,Graph,False,4039,88234,4039,88234,1,4039,...,1.000000,1.000000,0.010820,43.691013,0.605547,0.519174,0.063577,1,ego_facebook,SNAP
7,socfb-Middlebury45,social,Graph,False,3075,124610,3075,124610,4,3069,...,0.998049,0.999976,0.026468,81.203649,0.282180,0.210842,0.078415,1,socfb_middlebury45,Network Data Repository

In [3]:
dataset_manifest

,network_id,network,domain,repository,source_url,source_file,source_sha256,graph_file,processed_file
0,email_eu_core,email-Eu-core,communication,SNAP,https://snap.stanford.edu/data/email-Eu-core.t...,email-Eu-core.txt.gz,4b47acdb80197b085fe63c819c357ae488131ee904ed93...,data/raw/email-Eu-core.txt,data/processed/email-Eu-core.edgelist
1,email_univ,email-univ,communication,Network Data Repository,https://nrvis.com/download/data/ia/ia-email-un...,ia-email-univ.zip,910de7179ec2268952c655f5137ea01b3179d9ecae1be8...,data/raw/email_univ/ia-email-univ.mtx,data/processed/email-univ.edgelist
2,power_1138_bus,power-1138-bus,infrastructure,Network Data Repository,https://nrvis.com/download/data/power/power-11...,power-1138-bus.zip,2239bc438049e971b8b1d3ccb95d404f2a8ec5fe727185...,data/raw/power_1138_bus/power-1138-bus.mtx,data/processed/power-1138-bus.edgelist
3,power_grid,power-grid,infrastructure,Netzschleuder,https://networks.skewed.de/net/power/files/pow...,power.csv.zip,66c051841053af1ebe488973fb579ff4f723566dc2ee28...,data/raw/power_grid/edges.csv,data/processed/power-grid.edgelist
4,ca_grqc,ca-GrQc,scientific_collaboration,SNAP,https://snap.stanford.edu/data/ca-GrQc.txt.gz,ca-GrQc.txt.gz,a254442cdf5d684712578b630c2e0d7543518ab154ef23...,data/raw/ca-GrQc.txt,data/processed/ca-GrQc.edgelist
5,ca_hepth,ca-HepTh,scientific_collaboration,SNAP,https://snap.stanford.edu/data/ca-HepTh.txt.gz,ca-HepTh.txt.gz,7235c7e11887f8a32dfd03a3aa0c77efdf89d41591a959...,data/raw/ca-HepTh.txt,data/processed/ca-HepTh.edgelist
6,ego_facebook,ego-Facebook,social,SNAP,https://snap.stanford.edu/data/facebook_combin...,facebook_combined.txt.gz,125e84db872eeba443d270c70315c256b0af43a502fcfe...,data/raw/facebook_combined.txt,data/processed/ego-Facebook.edgelist
7,socfb_middlebury45,socfb-Middlebury45,social,Network Data Repository,https://nrvis.com/download/data/socfb/socfb-Mi...,socfb-Middlebury45.zip,6daae42cd36567698690de59976de4be73debb666a7616...,data/raw/socfb_middlebury45/socfb-Middlebury45...,data/processed/socfb-Middlebury45.edgelist